import { useEffect, useState } from 'preact/hooks';
import { useWs } from '../context';
import { CATEGORY_LABEL, coverConcept, roleAnalysis, summarize } from '../engine/coverage';
import { analyzeJD } from '../engine/jd';
import { parseJDRemote } from '../api';
import { track } from '../analytics';
import type { CoverageAnalysis } from '../engine/types';
import { CoverageBar, EvidenceMap } from './charts';
import { ReqList } from './Blocks';

export function shareLink(a: CoverageAnalysis): string {
  const base = location.origin + location.pathname;
  if (a.source === 'role' && a.roleId) return `${base}#imw=role:${a.roleId}`;
  // Job descriptions are shared as detected requirement ids only, never as pasted text.
  const ids = a.requirements.map((r) => r.id).filter((id) => !id.startsWith('term:')).join(',');
  return `${base}#imw=role:${encodeURIComponent(`jd~${ids}`)}`;
}

export function markdownSummary(a: CoverageAnalysis, kbName: string): string {
  const lines = [`# Evidence coverage: ${a.title}`, `Candidate: ${kbName}`, ''];
  for (const cat of ['direct', 'related', 'verification', 'missing'] as const) {
    const reqs = a.requirements.filter((r) => r.category === cat);
    if (!reqs.length) continue;
    lines.push(`## ${CATEGORY_LABEL[cat]} (${reqs.length})`);
    reqs.forEach((r) => lines.push(`- ${r.label}${r.statement && cat !== 'direct' ? ` — ${r.statement}` : ''}`));
    lines.push('');
  }
  if (a.notes.length) lines.push(...a.notes.map((n) => `> ${n}`), '');
  lines.push(`Generated by Interview My Work from verified evidence. No fit score is computed.`);
  return lines.join('\n');
}

export function RoleView() {
  const { kb, coverage, setCoverage, modeArg, api, toggleLens, ask, go } = useWs();
  const [tab, setTab] = useState<'role' | 'jd'>(modeArg === 'jd' ? 'jd' : 'role');
  const [jd, setJd] = useState('');
  const [refining, setRefining] = useState(false);
  const [copied, setCopied] = useState('');

  useEffect(() => {
    if (!modeArg) return;
    if (modeArg === 'jd') { setTab('jd'); return; }
    const arg = decodeURIComponent(modeArg);
    if (kb.role.has(arg)) setCoverage(roleAnalysis(kb, arg));
    else if (arg.startsWith('jd~')) {
      const ids = arg.slice(3).split(',').filter(Boolean);
      const reqs = ids.map((id) => (id.startsWith('near:') ? coverConcept(kb, (kb.skills.find((s) => s.near?.includes(id.slice(5)))?.id) ?? id, { near: id.slice(5) }) : coverConcept(kb, id)));
      setCoverage(summarize(kb, 'Shared job description', reqs, { source: 'jd' }));
    }
  }, [modeArg]);

  const pickRole = (id: string) => {
    if (!id) return;
    setCoverage(roleAnalysis(kb, id));
    track('role_selected', { role: id });
  };

  const runJD = () => {
    if (jd.trim().length < 40) return;
    const a = analyzeJD(kb, jd);
    setCoverage(a);
    track('jd_analyzed', { requirements: a.requirements.length });
    if (api === 'ready') {
      setRefining(true);
      parseJDRemote(jd).then((phrases) => { if (phrases.length) setCoverage(analyzeJD(kb, jd, phrases), a); }).catch(() => {}).finally(() => setRefining(false));
    }
  };

  const copy = async (what: 'link' | 'md') => {
    if (!coverage) return;
    try {
      await navigator.clipboard.writeText(what === 'link' ? shareLink(coverage) : markdownSummary(coverage, kb.subject.name));
      setCopied(what);
      setTimeout(() => setCopied(''), 2000);
    } catch { /* clipboard unavailable */ }
  };

  const priority = kb.roles.filter((r) => r.priority).sort((a, b) => a.priority! - b.priority!);
  const tiers = [['strong', 'Strong fit'], ['adjacent', 'Adjacent'], ['stretch', 'Stretch']] as const;

  return (
    <div class="imw-view">
      <header class="imw-view-head">
        <div class="imw-eyebrow">Evaluate against a role</div>
        <h3 data-autofocus tabIndex={-1}>What are you evaluating Rahul for?</h3>
        <p class="imw-help">Each requirement is classified as direct evidence, related evidence, verification required, or not currently demonstrated. There is no match percentage.</p>
      </header>

      <div class="imw-seg" role="tablist" aria-label="Input">
        <button role="tab" aria-selected={tab === 'role'} class={tab === 'role' ? 'is-on' : ''} onClick={() => setTab('role')}>Select a role</button>
        <button role="tab" aria-selected={tab === 'jd'} class={tab === 'jd' ? 'is-on' : ''} onClick={() => setTab('jd')}>Paste a job description</button>
      </div>

      {tab === 'role' ? (
        <div class="imw-rolepick">
          <div class="imw-role-cards">
            {priority.map((r) => (
              <button key={r.id} class={coverage?.roleId === r.id && coverage.source === 'role' ? 'is-on' : ''} onClick={() => pickRole(r.id)}>
                <strong>{r.title}</strong>
                <small>{r.proof_note}</small>
              </button>
            ))}
          </div>
          <label class="imw-select">
            <span>More roles</span>
            <select onChange={(e) => pickRole((e.target as HTMLSelectElement).value)} value={coverage?.source === 'role' ? coverage.roleId : ''}>
              <option value="">Choose a role…</option>
              {tiers.map(([t, label]) => (
                <optgroup key={t} label={label}>
                  {kb.roles.filter((r) => r.tier === t && !r.priority).map((r) => <option key={r.id} value={r.id}>{r.title}</option>)}
                </optgroup>
              ))}
            </select>
          </label>
        </div>
      ) : (
        <div class="imw-jd">
          <label class="sr-only" for="imw-jd">Job description</label>
          <textarea id="imw-jd" rows={8} value={jd} maxLength={12000} placeholder="Paste the full job description, including requirements and nice-to-haves."
            onInput={(e) => setJd((e.target as HTMLTextAreaElement).value)} />
          <div class="imw-row">
            <button class="imw-btn is-primary" onClick={runJD} disabled={jd.trim().length < 40}>Analyze coverage</button>
            <span class="imw-help">
              {api === 'ready' ? 'Parsed in your browser, then refined by the AI parser. The text is not stored.' : 'Parsed in your browser. Nothing is sent anywhere.'}
            </span>
          </div>
        </div>
      )}

      {coverage && (
        <section class="imw-analysis" aria-live="polite">
          <div class="imw-analysis-head">
            <div>
              <div class="imw-eyebrow">Evidence coverage{refining ? ' · refining with AI…' : ''}</div>
              <h3>{coverage.title}</h3>
              {coverage.source === 'jd' && coverage.closestRole && <p class="imw-help">Closest target profile: {coverage.closestRole}</p>}
            </div>
            <div class="imw-row">
              <button class="imw-btn is-primary" onClick={() => toggleLens(true)}>Show this on the portfolio</button>
              <button class="imw-btn" onClick={() => go('brief')}>10-minute brief</button>
            </div>
          </div>
          <CoverageBar counts={coverage.counts} />
          {coverage.notes.map((n) => <p key={n} class="imw-note">{n}</p>)}
          <EvidenceMap analysis={coverage} max={18} />
          <ReqList analysis={coverage} />
          <div class="imw-actions">
            <button class="imw-btn" onClick={() => ask(coverage.roleId ? `Challenge the evidence for ${coverage.title}` : 'Challenge this evidence')}>Challenge this evidence</button>
            <button class="imw-btn" onClick={() => go('map', coverage.roleId)}>View on the evidence map</button>
            <button class="imw-btn" onClick={() => copy('link')}>{copied === 'link' ? 'Link copied' : 'Copy shareable link'}</button>
            <button class="imw-btn" onClick={() => copy('md')}>{copied === 'md' ? 'Summary copied' : 'Copy summary'}</button>
            <button class="imw-btn" onClick={() => go('export')}>Download PDF</button>
          </div>
        </section>
      )}
    </div>
  );
}
